# Generated by Django 4.2.7 on 2023-11-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_alter_recipe_options_recipe_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to="images/uploaded/"),
        ),
    ]
