[tool.black]
line-length = 120
target-version = ['py311']
include = '\.py$'
exclude = '''
(
    migrations
    | /.tox
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
skip_glob = "*/migrations/*.py"
